name: Build and Test

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Test with Gradle
      run: ./gradlew test
    
    - name: Archive JAR artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jars
        path: |
          server/build/libs/taskmanagement-server.jar
          cli/build/libs/taskmanagement-cli.jar
